##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wvyiuzji/public_html/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp _redirects $DEPLOYPATH
    - /bin/cp duc.txt $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH